// <auto-generated />
using GUtv_backend_dotnet.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GUtv_backend_dotnet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603120000_AddUserAvatarSeed")]
    partial class AddUserAvatarSeed
    {
    }
}
