using GUtv_backend_dotnet.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace GUtv_backend_dotnet.Migrations
{
    /// <inheritdoc />
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412171402_AddCartSync")]
    public partial class AddCartSync : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // This migration was previously undiscoverable. Existing installations may
            // have created the cart tables manually, so adopt them without deleting data.
            migrationBuilder.Sql(
                """
                CREATE TABLE IF NOT EXISTS "Carts" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "UserId" integer NOT NULL,
                    "Reason" text NOT NULL,
                    "StartTime" timestamp with time zone,
                    "EndTime" timestamp with time zone,
                    "Comment" text,
                    "UpdatedAt" timestamp with time zone NOT NULL,
                    CONSTRAINT "PK_Carts" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_Carts_Users_UserId" FOREIGN KEY ("UserId")
                        REFERENCES "Users" ("Id") ON DELETE CASCADE
                );

                CREATE TABLE IF NOT EXISTS "CartItems" (
                    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
                    "CartId" integer NOT NULL,
                    "EqModelId" integer NOT NULL,
                    "Quantity" integer NOT NULL,
                    CONSTRAINT "PK_CartItems" PRIMARY KEY ("Id"),
                    CONSTRAINT "FK_CartItems_Carts_CartId" FOREIGN KEY ("CartId")
                        REFERENCES "Carts" ("Id") ON DELETE CASCADE,
                    CONSTRAINT "FK_CartItems_EqModels_EqModelId" FOREIGN KEY ("EqModelId")
                        REFERENCES "EqModels" ("Id") ON DELETE CASCADE
                );

                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Carts_UserId"
                    ON "Carts" ("UserId");
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_CartItems_CartId_EqModelId"
                    ON "CartItems" ("CartId", "EqModelId");
                CREATE INDEX IF NOT EXISTS "IX_CartItems_EqModelId"
                    ON "CartItems" ("EqModelId");
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CartItems");

            migrationBuilder.DropTable(
                name: "Carts");
        }
    }
}
